- name: Install PostgreSQL and create schemas
  hosts: all
  become: yes

  tasks:
    - name: Install PostgreSQL server package
      dpkg:
        deb: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        update_cache: yes
        package: postgresql-14
        force: yes
        force_confnew: yes

    - name: Install Python3
      apt:
        name: python3
        state: latest
        update_cache: yes

    - name: Install psycopg2 package
      apt:
        name: python3-psycopg2
        state: latest
        update_cache: yes

    - name: Stop PostgreSQL service
      systemd:
        name: postgresql
        state: stopped

    - name: Remove PostgreSQL cluster
      shell: pg_dropcluster 14 main --stop
      become_user: postgres
      become: yes

    - name: Initialize PostgreSQL database
      shell: pg_createcluster 14 main --start
      become_user: postgres
      become: yes

    - name: Start PostgreSQL service and enable it on boot
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Wait for PostgreSQL service to start
      wait_for:
        port: 5432
        timeout: 60

    - name: Create PostgreSQL schemas
      postgresql_query:
        login_user: postgres
        login_password: mysecretpassword
        db: postgres
        query: "CREATE SCHEMA IF NOT EXISTS ENERGY; CREATE SCHEMA IF NOT EXISTS PASST; CREATE SCHEMA IF NOT EXISTS NETWORK;"

    - name: Allow remote access to PostgreSQL
      lineinfile:
        dest: /etc/postgresql/14/main/pg_hba.conf
        line: "host    all             all             0.0.0.0/0            md5"
        insertafter: "^# TYPE DATABASE USER"
        state: present
        create: yes
      notify: restart postgresql

    - name: Update PostgreSQL configuration
      lineinfile:
        dest: /etc/postgresql/14/main/postgresql.conf
        regexp: "^#?listen_addresses = 'localhost'$"
        line: "listen_addresses = '*'"
        state: present
        create: yes
      notify: restart postgresql

  handlers:
    - name: Restart PostgreSQL service
      systemd:
        name: postgresql
        state: restarted
